version: '3'

networks:

  nw_f:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

  nw_m:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.20.0/24

  nw_b:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.30.0/24

  nw_a:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.40.0/24

services:

  front:
    image: nginx:${VER_NGINX}-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nw_f
      - nw_m
    links:
      - middle:upstream
    command: nginx -g 'daemon off;'

  middle:
    image: nginx:${VER_NGINX}-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nw_m
      - nw_b
    links:
      - back:upstream
    command: nginx -g 'daemon off;'

  back:
    image: nginx:${VER_NGINX}-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nw_b
      - nw_a
    links:
      - app:upstream
    command: nginx -g 'daemon off;'

  app:
    image: node:${VER_NODE}-alpine
    expose:
      - "80"
    networks:
      - nw_a
    volumes:
      - ./app:/app:ro
      - ./app/node_modules:/node_modules:ro
    working_dir: /app
    command: node app.js

